server:
  port: 9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zipkin-server
  sleuth:
    sampler:
      percentage: 1.0
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

zipkin:
  storage:
    type: mysql

#spring.sleuth.sampler.percentage: 1.0
