eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false

server:
  port: 8762

logging:
  file: "logs/eureka-client-one.log"

spring:
  application:
    name: eureka-client-one
