spring:
  application:
    name: service-authorization

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  context-path: /service-auth
security:
  oauth2:
    resource:
      filter-order: 3
  basic:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/